### PR TITLE
create reproducible jar

### PR DESCRIPTION
**Pull request by hboutemy**
Jar created by Antrun is not reproducible by default
creating it with maven-jar-plugin gives reproducible one

please merge also #138

### CODE REVIEW

**Review by rishabhdaim — APPROVED** [review]

**Comment by hboutemy** [comment]
@rishabhdaim this PR was approved but not merged: what can I do to have #139 and #138 merged?

**Comment by reschke** [comment]
Jackrabbit classic still is on SVN.

Please create a JIRA ticket on component "JCR", describe the issue, and attach the patch (or link to this PR).

**Comment by hboutemy** [comment]
thanks for the feedback @reschke 
done https://issues.apache.org/jira/browse/JCR-4980

**Comment by hboutemy** [comment]
merged

**Pull request closed without merging**
