### PR TITLE
JCR-4536: Feature/enable insecure https host

### PR DESCRIPTION
**Pull request by wildone**
Adding support for insecure parameter to allow access to https with invalid certs.

Enabling optional support for expired ssl certs when using https on development server with self generated certificates.

### CODE REVIEW

**Comment by kwin** [comment]
I don't see a related JIRA ticket. @wildone Can you create one?

**Comment by wildone** [comment]
@kwin is there anything else needed?

**Comment by kwin** [comment]
There was some feedback from @reschke in https://issues.apache.org/jira/browse/JCR-4536?focusedCommentId=17055667&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17055667.

**Comment by wildone** [comment]
thank @kwin do you want me to add logging to prompt the user that insecure option being used? Any preference what the message for prompt should be?

**Comment by kwin** [comment]
Obsoleted by https://github.com/apache/jackrabbit/pull/92.

**Pull request closed without merging**
