### PR TITLE
JCR-4766: correct json response content type

### PR DESCRIPTION
**Pull request by woonsan**

### CODE REVIEW

**Comment by woonsan** [comment]
Hello @reschke ,
Would you mind reviewing this bug fix?
Thanks in advance,
Woonsan

**Comment by reschke** [comment]
The change in itself looks right to me. My only concern would be that there is client code which might rely on the incorrect type. But that should be covered by integration tests, right. @anchela ?

**Review by anchela — APPROVED** [review]
looks good to me. thanks.

**Comment by anchela** [comment]
@anchela , i am not entirely sure it is covered by ITs but fixing the wrong time makes sense. I am aware of a few usages in client code and think they could be adjusted in case they really relied on the incorrect type. Maybe they don't care and therefore never noticed the wrong type.

**Comment by reschke** [comment]
Applied as http://svn.apache.org/r1899805

**Pull request closed without merging**
